### ISSUE TITLE
DIR_COLORS is missing tmux entries

### ISSUE THREAD

**Issue by amonakov** [openSUSE/aaa_base#116]
DIR_COLORS is out of date with respect to dircolors.hin from coreutils upstream [1], and as such is missing TERM entries for tmux and probably some other useful additions.

[1] https://github.com/coreutils/coreutils/blob/master/src/dircolors.hin

**Comment by bugfinder** [comment]
fixed in 0591555d6ed8cad378bdf2be6369e2150c70d701
