### ISSUE TITLE
/usr/etc/profile.d/alljava.csh issue

### ISSUE THREAD

**Issue by gcomes** [openSUSE/aaa_base#144]
There are a couple of problems in the file alljava.csh after commit:
  056fc66c699a8544c7692a03c905fca568f5390b
There is a misspelling JAVA_HOME/JAVA_BINDIR and 
a wrong std-error redirection not present in the commit 
in the repository and in the patch for leap 15.6, but
present in the patch for leap 15.5 and in the tumbleweed source.
Please see boo#1221361 for all the details.

**Comment by bugfinder** [comment]
fixed in 294367193d39225afb2d9490a8a7610581817261
