### ISSUE TITLE
wrong window title via bash.bashrc

### ISSUE THREAD

**Issue by lnussel** [openSUSE/aaa_base#146]
bash.bashrc has some magic to set the window title of terminals. For xterm, gnome, konsole and xfce there is special treatment setting $_isl. Other terminals such as foot enter a different code path which leads to a differnt $TS1. The length check later in the ppwd function seems to be fragile though. In case of foot at least TS1 seems to be longer than 17 characters, leading to a title like `hostname@:` instead of `user@hostname:path`

**Comment by lnussel** [comment]
alacritty and cool-retro-term work. Foot behaves as described. Kitty only shows the path in the title

**Comment by bugfinder** [comment]
okay, fixes merged and forwarded to factory, closing
