### ISSUE TITLE
lang.sh: all RC_* values ignored if RC_LANG is set

### ISSUE THREAD

**Issue by datamaan** [openSUSE/aaa_base#29]
https://github.com/openSUSE/aaa_base/blob/master/files/etc/profile.d/lang.sh#L33
Due to this line all RC_* values are essentially ignored when RC_LANG is of non-zero length.

Is this intended behavior? If so, could you explain to me why?

I noticed this since I wanted to use this configuration:

    RC_LANG="de_DE.UTF-8"
    RC_LC_MESSAGES="en_US.UTF-8"

but the second line is ignored.
Doesn't this line have to be `test -z "$LANG" && continue` ?

**Comment by bitstreamout** [comment]
On Sun, May 01, 2016 at 07:22:04PM -0700, Stefan L wrote:
> https://github.com/openSUSE/aaa_base/blob/master/files/etc/profile.d/lang.sh#L33
> Due to this line all RC_* values are essentially ignored when RC_LANG is of non-zero length.
> 
> Is this intended behavior? If so, could you explain to me why?
> 
> I noticed this since I wanted to use this configuration:
> 
>     RC_LANG="de_DE.UTF-8"
>     RC_LC_MESSAGES="en_US.UTF-8"
> 
> but the second line is ignored.
> Doesn't this line have to be `test -z "$LANG" && continue` ?

... Ah ... no ... it would be better to use

   test -n "$GDM_LANG" && continue

as GNOME desktop should be able to overwrite system setting
at login done by GDM

Thanks for spotting

Werner

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by datamaan** [comment]
That makes sense. Thanks for explaining.
