### ISSUE TITLE
Setting HOST variable in /etc/profile breaks build environments

### ISSUE THREAD

**Issue by prusnak** [openSUSE/aaa_base#38]
Some build environments set variable called `HOST` to output of `config.guess` if it has not been specified by user and the value looks like this `x86_64-unknown-linux-gnu`.

In openSUSE /etc/profile sets HOST in env to hostname, which overrides the detection and thus breaks these build environments.

For reference: CentOS and Debian don't set this variable and probably use HOSTNAME variable which is also set on openSUSE.

**Comment by lnussel** [comment]
we have that set probably since the beginning of time. Do you have an example of where it happens and when it why it was introduced?

**Comment by prusnak** [comment]
See this for example:

https://github.com/zcash/zcash/blob/master/depends/Makefile#L19-L22

**Comment by coolo** [comment]
the argument is a bit strange. Using $HOST because it's standard autoconf - but not using standard autoconf. Because what they call $HOST in there is the output of config.guess unless cross compiled - which they assign to BUILD.

You might not see the Makefile bug on other platforms, but that still makes it less of a Makefile bug. If they want to use autoconf, they should :)

**Comment by prusnak** [comment]
I agree with you, coolo, that their build system is rather strange. I had encountered this error for the first time and I use openSUSE for more than 10 years now, so I guess it's not a world-wide problem really.

Rather, maybe, I wanted to ask why it is defined as opposed to other distros. It seems that's some relic from the past and most probably nobody know, so feel free to close and ignore.

**Comment by daira** [comment]
Yeah this is our bug: https://github.com/zcash/zcash/issues/2285#issuecomment-296195137

Feel free to close this.

**Comment by dnut** [comment]
This also causes a problem building react apps. No other linux distros use this variable, so it's inevitably going to lead to issues because it sets a widely used name that is expected to be unset.
