### ISSUE TITLE
ls.bash problem

### ISSUE THREAD

**Issue by Ximi1970** [openSUSE/aaa_base#54]
My gitlab service stopped working due to a change in ls.bash.

The line: `    function _ls {`

in /etc/profile.d/ls.bash will result in the error:
` /etc/profile.d/ls.bash: Syntax error: "}" unexpected (expecting ";;")`

changing the line into:
`     function _ls`
`     {`

solves this error.

**Comment by bugfinder** [comment]
fixed since Apr 9h 2018 by werner
