### ISSUE TITLE
Bump LEAP release

### ISSUE THREAD

**Issue by cornfeedhobo** [openSUSE/aaa_base#97]
@bitstreamout Would it be possible to get a new release pushed out for LEAP 15.x?

see related [ticket](https://code.opensuse.org/leap/features/issue/44)

**Comment by bitstreamout** [comment]
This is IMHO a bad idea as aaa_base is developed for Tumbleweed. That is backporting a commit or part of  to a former relase of aaa_base done for Leap/SLES does work whereas the full tree is likely breaking any Leap or SLES out there

**Comment by cornfeedhobo** [comment]
@bitstreamout I'm not sure I follow. I'm currently running the TW aaa_base package on 2 different LEAP installs. It works well. Can you elaborate on your concerns? LEAP has automated integration testing that should catch issues, and the current package **breaks shells** in LEAP. I see bumping the package as a bug fix.

**Comment by cornfeedhobo** [comment]
@bitstreamout I think it's bad practice for OpenSuse to keep treating LEAP users like second class citizens. Many of the changes here not reaching LEAP mean that users of a **LTS** distro are stuck with a **broken** environment in some cases. I think you should reconsider brushing this off.

**Comment by bitstreamout** [comment]
On 2021/09/28 14:55:38 -0700, cornfeedhobo wrote:
> @bitstreamout I think it's bad practice for OpenSuse to keep treating LEAP users like second class citizens. Many of the changes here not reaching LEAP mean that users of a **LTS** distro are stuck with a **broken** environment in some cases. I think you should reconsider brushing this off.
> 

I've not made the rules!  Nevertheless the rules are clear even if you set
a dislike: Never override a certified SLES package by a dumb version upgrade.
And Leap is based on SLES.  It might that this works for your Leap systems,
but does this work for all SLES customers and Leap users out there?  And this
even after /usr merge and move the /etc distribution configs to /usr/etc
and adding and/or removing various configuration files?

If you have a bug for Leap then please open a bugzilla entry for this specific
topic and if valid the fitting commit can be back ported to Leap.

Thanks

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by cornfeedhobo** [comment]
@bitstreamout Okay, if this is tied so tightly to SLES, and you are aware that you are merging stuff that should be backported, why is this task left to unwitting users?

**Comment by bitstreamout** [comment]
I was not aware that 8-bit Controls of e.g. XTerm are a deep problem nor a bug in Leap.

**Comment by cornfeedhobo** [comment]
@bitstreamout It's sad that you felt the need to belittle this request. It's really a bad representation of the opensuse community. I'll take this up elsewhere.
